### PR TITLE
Small fix for magnum networking

### PR DESCRIPTION
**Pull request by darmach**
External subnet was missing gateway (pointing to seed node).
While spawning cluster was failing to pull containers.

### CODE REVIEW

**Comment by Alex-Welsh** [comment]
I think you want to point this at https://github.com/stackhpc/terraform-kayobe-multinode

**Comment by Alex-Welsh** [comment]
And I think we've patched the same thing https://github.com/stackhpc/openstack-config-multinode/commit/f7729eb5ac3454cffba62731a7a36e7566d55676

**Comment by darmach** [comment]
> I think you want to point this at https://github.com/stackhpc/openstack-config-multinode

Ah definitely, thanks

**Comment by darmach** [comment]
> And I think we've patched the same thing [stackhpc@f7729eb](https://github.com/stackhpc/openstack-config-multinode/commit/f7729eb5ac3454cffba62731a7a36e7566d55676)

Indeed that's a double tap on the same issue! :)

**Pull request closed without merging**
